name: Check for updates
on:
#  schedule:
#    - cron: '*/15 * * * *'

  push:
    branch:
      - '**'
jobs:
  scan:
    name: List Recent Updates
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: latest-image
        continue-on-error: true
      - name: get image
        run: |
             RESULT_NEW=$(curl -s https://registry.hub.docker.com/v2/repositories/sigp/lighthouse/tags |jq -r '.results[] |select(.name |test("v[0-9]+.[0-9]+.[0-9]+-modern"))|.name')
             if [ -f RESULT];then  RESULT=${< RESULT};fi
             echo "$RESULT $RESULT_NEW"
             if [ "$RESULT" != "$RESULT_NEW" ]; then echo "::set-output name=TRIGGER::true";fi
             echo "::set-output name=LATEST_RESULT::${RESULT_NEW}"
             echo "${RESULT_NEW}" > RESULT
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.LATEST_RESULT }}'"
      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.5
        if: steps.scan.outputs.TRIGGER
        with:
          tag_name: ${{ steps.scan.outputs.LATEST_RESULT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: latest-image
          path: RESULT
          retention-days: 2
