name: Check for updates
on:
  schedule:
    - cron: '9 9 * * *'

  push:
    tag:
      - '**'
jobs:
  scan:
    name: List Recent Updates
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: scan.yml
          workflow_conclusion: success
          name: latest-image
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: .
          if_no_artifact_found: warn
      - name: test
        run: cat RESULT
        continue-on-error: true
      - name: get image
        run: |
             RESULT_NEW=$(curl -s https://registry.hub.docker.com/v2/repositories/sigp/lighthouse/tags |jq -r '.results[] |select(.name |test("v[0-9]+.[0-9]+.[0-9]+-modern"))|.name')
             if [ -f ./RESULT ];then  RESULT=$(cat ./RESULT);fi
             echo "$RESULT $RESULT_NEW"
             if [ "$RESULT" != "$RESULT_NEW" ]; then echo "::set-output name=TRIGGER::'true'";fi
             echo "::set-output name=LATEST_RESULT::${RESULT_NEW}"
             echo "${RESULT_NEW}" > RESULT
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.LATEST_RESULT }}'"
      - name: Print
        run: "echo 'Trigger: ${{ steps.scan.outputs.TRIGGER }}'"
      - name: Tag commit
        if: ${{ steps.scan.outputs.TRIGGER }} == 'true'
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.ACCESS_TOKEN }}"
          tag: "${{ steps.scan.outputs.LATEST_RESULT }}"
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: latest-image
          path: RESULT
          retention-days: 2
